server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
  rootPath: /rest-api/*

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3306/inmobi